---

- name: Dev env setup
  hosts: local

  tasks:

  - name: Tap caskroom/fonts for powerline fonts
    homebrew_tap:
      name: homebrew/cask-fonts

  # - name: Tap caskroom/versions for edge versions
  #   homebrew_tap:
  #     name: homebrew/cask-versions

  - name: Install fonts
    homebrew_cask:
      name: font-firacode-nerd-font

  - name: Install neovim
    homebrew:
      name: neovim
      install_options: HEAD

  - name: Install other utilities
    homebrew:
      name: ['ruby', 'rbenv', 'zsh-syntax-highlighting', 'ctags', 'fortune', 'node', 'diff-so-fancy']

  - name: Add node support for neovim
    npm:
      name: neovim
      global: yes

  - name: Add ruby support for neovim
    gem:
      name: neovim

  - name: Add python support for neovim
    pip:
      name: neovim
      executable: pip3

  - name: Remove the default zshrc file
    file:
      path: ~/.zshrc
      state: absent

  - name: Create config directory for neovim
    file:
      path: ~/.config/nvim/
      state: directory

  - name: Symlink the config file for zsh
    file:
      src: "$HOME/dotfiles/.zshrc"
      dest: "$HOME/.zshrc"
      state: link
      force: yes
      follow: false

  - name: Symlink the cobalt theme to oh my zsh
    file:
      src: "$HOME/dotfiles/cobalt2.zsh-theme"
      dest: "$ZSH/themes/cobalt2.zsh-theme"
      state: link
      force: yes
      follow: false

  - name: Clone zsh-autosuggestions to oh-my-zsh
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "$ZSH/custom/plugins/zsh-autosuggestions"

  - name: Clone zsh-completions to oh-my-zsh
    git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: "$ZSH/custom/plugins/zsh-completions"

  - name: get the afterglow theme to the home directory
    get_url:
      url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Afterglow.itermcolors
      dest: "$HOME/Afterglow.itermcolors"

  - name: Specify the preferences directory for iterm2 preferences
    command: defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/iterm2"

  - name: Tell iTerm2 to use the custom preferences in the above specifed directory
    command: defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

  - name: Symlink the neovim config files
    file:
      src: "$HOME/dotfiles/nvim/{{ item.src }}"
      dest: "$HOME/.config/nvim/{{ item.dest }}"
      state: link
      force: yes
      follow: false
    with_items:
      - { src: init.vim, dest: init.vim }
      - { src: colorschemes.vim, dest: colorschemes.vim }
      - { src: abbrev.vim, dest: abbrev.vim }
      - { src: key_mappings.vim, dest: key_mappings.vim }
      - { src: plugins_list.vim, dest: plugins_list.vim }
      - { src: plugin_settings.vim, dest: plugin_settings.vim }

  - name: Symlink the neovim colorscheme
    file:
      src: "$HOME/dotfiles/nvim/colors"
      dest: "$HOME/.config/nvim/colors"
      state: link
      force: yes
      follow: false

  - name: Symlink the gitignore file
    file:
      src: "$HOME/dotfiles/global_gitignore"
      dest: "$HOME/.gitignore_global"
      state: link
      force: yes
      follow: false

  - name: Symlink the git_template directory
    file:
      src: "$HOME/dotfiles/.git_template"
      dest: "$HOME/.git_template"
      state: link
      force: yes
      follow: false

  - name: Symlink the git config file
    file:
      src: "$HOME/dotfiles/.gitconfig"
      dest: "$HOME/.gitconfig"
      state: link
      force: yes
      follow: false

  - name: Symlink the short dir alias file
    file:
      src: "$HOME/dotfiles/short-dir.zsh"
      dest: "$ZSH/custom/short-dir.zsh"
      state: link
      force: yes
      follow: false

  - name: Symlink the docker alias file
    file:
      src: "$HOME/dotfiles/docker-rails.zsh"
      dest: "$ZSH/custom/docker-rails.zsh"
      state: link
      force: yes
      follow: false

  - name: Uninstall the ruby installed by homebrew
    homebrew:
      name: ruby
      state: absent
